//ライブラリ設定
#include "DxLib.h"
#include <math.h>
#include <stdio.h>
#include <windows.h>
#include <time.h>
#define PI	3.1415926535897932384626433832795f
#define ANIME	11
//関数定義
int sentou_main();//戦闘のメイン
int senjyutu_nedan();
int omake_main();//おまけモードメイン
int omake_save();//おまけモード自動セーブ
int omake_load();//おまけモード自動ロード
int re_start();
int shot_main();//間接攻撃
int sentou_kaisi();//戦闘開始前の初期化
int sentou_ai();//戦闘時のＡＩ処理
int sentou_command();//戦闘中のコマンド選択
int sentou_byouga();//戦闘中の描画処理
int sentou_atari();//戦闘中の当たり判定
int sentou_battle();//衝突時のダメージ判定
int sentou_idou();//戦闘中の移動判定
int sekaitizu();//政治モードメイン
int hikari();
int naisei_command();
int gaikou_command();
int title();
int syouri_bonus();
int ex_wasure();
void fire_atari();
void saku_atari();
void ana_atari();
int waku(int xa,int ya,int xb,int yb);
int waku_2(int xa,int ya,int xb,int yb);
int hukidasi();
int command_mes();
int AIsentou_check();
int sekai_byouga();
int hukoku_dai();
int hirameki();
int jin_01();
int jin_02();
int jin_03();
int jin_04();
int jin_05();
int jin_06();
int jin_07();
int jin_08();
int jin_09();
int jin_10();
int jin_11();
int jin_12();
int jin_13();
int jin_14();
int jin_15();
int jin_16();
int jin_17();
int jin_18();
int jin_19();
int jin_20();
int jin_21();
int sen_01();
int sen_02();
int sen_03();
int sen_04();
int sen_05();
int sen_06();
int sen_07();
int sen_08();
int sen_09();
int sen_10();
int sen_11();
int sen_12();
int sen_13();
int sen_14();
int sen_15();
int sen_16();
int sen_17();
int sen_18();
int sen_19();
int sen_20();
int sen_21();
int sen_22();
int sen_23();
int sen_24();
int sen_25();
int sen_26();
int sen_27();
int sen_28();
int sen_29();
int sen_30();
int sen_31();
int sen_32();
int sen_33();
int sen_34();
int sen_35();
int sen_36();
int sen_37();
int sen_38();
int sen_39();
int sen_40();
int sen_41();
int sen_42();
int sen_43();
int sen_44();
int sen_45();
int sen_46();
int sen_47();
int sen_48();
int sen_49();
int sen_50();
int sen_51();
int sen_52();
int sen_53();
int sen_54();
int sen_55();
int sen_56();
int sen_57();
int sen_58();
int sen_59();
int sen_60();
int sen_61();
int sen_62();
int sen_63();
int sen_64();
int sen_65();
int sen_66();
int sen_67();
int AI_kihon();
int AI_VScheck();
int AI_kougeki();
int AI_koutai();
int hei_dai();
int hei_sort();
int jin_dai();
int jin_select();
int jinkei_mes();
int jinkei_narabi();
int narabi();
int kettyaku();
int AI_01();
int AI_02();
int AI_03();
int AI_04();
int AI_05();
int AI_06();
int AI_07();
int AI_08();
int AI_09();
int AI_10();
int AI_11();
int AI_12();
int AI_13();
int AI_14();
int AI_15();
int AI_16();
int AI_17();
int AI_18();
int AI_19();
int AI_20();
int AI_21();
int AI_22();
int AI_23();
int VS_01();
int VS_02();
int VS_03();
int VS_04();
int VS_05();
int VS_06();
int VS_07();
int VS_08();
int VS_09();
int VS_10();
int VS_11();
int VS_12();
int VS_13();
int VS_14();
int VS_15();
int VS_16();
int VS_17();
int VS_18();
int VS_19();
int VS_20();
int VS_21();
int VS_22();
int VS_23();
int VS_24();
int VS_25();
int VS_26();
int VS_27();
int VS_28();
int VS_29();
int VS_30();
int VS_31();
int VS_32();
int VS_33();
int VS_34();
int VS_35();
int VS_36();
int VS_37();
int VS_38();
int VS_39();
int VS_dai();
int eve_00();
int eve_01();
int eve_02();
int eve_03();
int eve_04();
int eve_05();
int eve_06();
int eve_07();
int eve_08();
int eve_09();
int eve_10();
int eve_11();
int eve_12();
int eve_13();
int eve_14();
int eve_15();
int eve_16();
int eve_17();
int eve_18();
int eve_19();
int eve_20();
int eve_21();
int eve_22();
int eve_23();
int eve_24();
int eve_25();
int eve_26();
int eve_27();
int eve_28();
int eve_29();
int eve_30();
int eve_31();
int eve_32();
int eve_33();
int eve_34();
int eve_35();
int eve_36();
int eve_37();
int eve_38();
int eve_39();
int eve_40();
int eve_41();
int eve_42();
int eve_43();
int eve_44();
int eve_45();
int eve_46();
int eve_47();
int eve_48();
int eve_49();
int eve_bunki();
int naisei_butai();
int naisei_zeikin();
int naisei_kougyou();
int naisei_buki();
int naisei_senjyutu();
int naisei_youhei();
int naisei_save();
int naisei_load();
int jinkei_name();
int hyouhou_name();
int jinkei_setumei();
int hyouhou_setumei();
int hyouhou_select();
int jinkei_select();
int kaisuu_set();
int data_save();
int data_load();
int jyouhou_kuni();
int jyouhou_teki();
int name_nyuuryoku();
int moji_load();
int syaberi();
int gaikou_command();
//変数定義
int hei_pow[2][100];//兵士の基本攻撃力
int hei_def[2][100];//兵士の基本防御力
int hei_wei[2][100];//兵士の基本踏ん張り
int hei_spd[2][100];//兵士の基本機動力
int hei_type[2][100];//兵士の兵種
int hei_down[2][100];//ダウン状態
int hei_sta[2][100];
int hyouji;
char event_tolk[2][3][100];
int hei_mov[2][100];//兵士の移動速度
int hei_kaz[2][100];//兵士の部隊数
int hei_dame[2][100];//兵士の少数点ダメージ
int hei_x[2][100];//兵士のＸ座標
int hei_y[2][100];//兵士のＹ座標
int hei_xnara[100];//陣形変化時のアニメ用
int hei_ynara[100];//陣形変化時のアニメ用
int hei_xnara2[100];//陣形変化時のアニメ用
int hei_ynara2[100];//陣形変化時のアニメ用
int hei_jin[2][100];//元の陣形の位置
int hei_muk[2][100];//兵士の向き
int hei_toppa[2][100];//兵士突破フラグ
int hei_time[2][100];//兵士の時間
int hei_osi[2][100];//兵士の押しの強さ
int hei_retu[2][100];//兵士の隊列 0前列、1後列
int hei_retu_syoki[2][100];//初期状態での隊列
int hei_sen[2][100];//兵士の戦闘状態
int hei_toku[2][100];//兵士の特殊状態残り時間
int hei_jyo[2][100];//兵士の状態異常
int hei_moral[2][100];//兵士の士気
int hei_syou[2][100];//兵士のモラル時間変化量
int hei_stop[2][100];//兵士の一時停止時間
int hei_sibou[2][100];//兵士死亡フラグ
int hei_ana[2][100];//落とし穴はまり状態
int hei_jump[2][100];//ジャンプした高さ
int hei_t1[2][100];//ジャンプ地点
int hei_t2[2][100];//着地地点
int hei_huki[2][100];//兵士の吹き飛ばされ量
int hei_emo[2][100];//噴出し表示フラグ用
int hei_esc[2][100];//逃走数
int hei_ren[2][100];//連続バトル係数
int hei_bom[2][100];//自爆フラグ
int hei_totu[2][100];//突撃状態フラグ
int hei_hirou[2][100];//兵士の疲労
int hei_atari[2][100];//兵士の当たり判定
int gun_sikikan[2];//指揮官生存フラグ

int hei_hura[2][100];//兵士フラッシュフラグ
int hei_vs[100];//兵士の攻撃フラグ

int job_vit[28];//兵士の基本生命力
int job_pow[28];//兵士の基本攻撃力
int job_def[28];//兵士の基本防御力
int job_wei[28];//兵士の基本踏ん張り
int job_spd[28];//兵士の基本機動力
int job_sta[28];//兵士のスタミナ

int dame_t[1000];//ダメージ表示残り時間
int dame_k[1000];//ダメージ量
int dame_x[1000];//ダメージ座標Ｘ
int dame_y[1000];//ダメージ座標Ｙ

int gun_moral[2];//軍の士気,平均値
int gun_hirou[2];//軍の疲労，平均値
int gun_toppa[2];//軍の突破人数
int gun_kazu[2];//軍の人数
int gun_nokori[2];//軍の残り兵力
int gun_change[2];//交代フラグ
int gun_frontline[2];//前列ライン保存用
int gun_backline[2];//後列ライン保存用
int gun_jinkai[2];//陣形回復用
int gun_sindahuri[2];//死んだフリ用
int gun_bom[2];

int gun_senjyutu[2][9];//装備している戦術
int gun_senrest[2][9];//各戦術の残使用回数

int gun_sentou[2];
int gun_jinkei[2];//軍が使用している陣形
int gun_retu[2];//前列のみor前列＆後列判定用
int meireihuka[2];//命令不可能状態
int ikari[2];//怒り表示用
int sirei_tame[2];//司令官の発動待
int shot_tame[2];//司令官の発動戦術
int butai_one[2];//部隊１の兵種
int butai_two[2];//部隊２の兵種
int butai_sirei[2];//司令官の兵種
int now_meirei[2];//最近使用した戦術
int now_time[2];//最近戦術を使用してからの時間
int sen_id[2][8];//セットしている戦術
int sen_rest[2][8];//戦術の残使用数
int front_line[2];//前列の位置
int back_line[2];//後列の位置
int i,j,c,J,A,B,t;
int jikan=0;
int map=6;
int siro,kuro,hai,aka,midori,ao,kougeki,bougyo,kaihuku;
int hatudou_kanou[2][9];//発動可能フラグ

int unit_g[28][3][12];//ユニットグラフィック
int world_map;//世界地図データ
int fire[4];
int ana,saku,huki,iwa;//障害物グラフィック
int saku_x[100];
int saku_y[100];
int saku_tai[100];//柵の耐久
int ana_x[100];//穴の位置
int ana_y[100];//穴の位置
int ana_id[100];//落とし穴のＩＤ
int fire_time[100];//火消滅までの時間
int fire_x[100];//火の座標
int fire_y[100];//火の座標
int fire_v[100];//火の移動速度
int AI_moral[2],AI_hirou[2],AI_damemax[2],AI_damemin[2],AI_dame[2],AI_line[2],AI_saikoubi[2];
int AI_bundan;
int AI_ueyoku[2];
int AI_sitayoku[2];
int AI_rest[63];//敵側残り戦術数
int ko_lineA=180*1000;//攻撃強制ラインA
int ko_lineB=120*1000;//後退不可ラインB
int ko_lineC=60*1000;//後退不可ラインC
int ko_moralA=9000;//後退解除モラル
int ko_moralB=7500;//後退解除モラル、対攻
int ko_moralC=5000;//攻撃続行モラル
int ko_moralD=0;//反撃モラル差
int ko_moralE=2000;//対無防備攻撃解除モラル
int ko_vsA=5;//対攻撃目標ダメージ
int ko_vsB=10;//対防御目標ダメージ　１０ぐらい
int ko_tousou=50000;//これ以上の疲労なら逃走
int ko_nigeru=20;//これ以下の部隊数なら逃走
int ko_totugeki=5000;//突撃するモラル差
int dorura;
//セーブする物
int set_jinkei[2];//編成している陣形
int set_hyouhou[2][9];//編成している兵法
int get_jinkei[20];//取得している兵法
int get_hyouhou[50];//所持している兵法
int flag_hyouhou[50];//兵法習得フラグ
int kuni_seiryoku[30];//国の勢力、０未発見、１自国、２同盟国、３敵国、４同盟不可能国
int kuni_henka[30];//国の勢力変化判定
int kuni_frash[30];//国の勢力変化アニメ用
int kuni_yuukou[30];//国の友好値。
int kuni_gundan[30];//その国の軍団
int kuni_type[30];//その国の表示アイコン
char kuni_name[30][22];//その国の名前
int youhei_lv[2];
int sinobi_lv[2];
int money;//国庫の金
int minsyuu;//民衆の評価
int sangyou;//国の産業レベル
int hiduke;//日付
int vs_count;
int win_count;//勝利回数
int lost_count;//敗北回数
int esc_count;//逃走回数
int anihi_count;//撃破数
int perfe_count;//無傷数
int eve_flag[100];//イベントフラグ
int get_item[20];//取得アイテム

int omake_mode;//おまけモードフラグ
int kuni_x[30];//国のＸ座標
int kuni_y[30];//国のＹ座標
int mouse;
int mouse_left;
int mouse_on;
int mou_x,mou_y;
int no[10];//数字
int emo[10];//感情噴出し
int sys_g;
int xa,xb,ya,yb;
int serihu_long;
int serihu_long2;
int f_a;
int f_t;//sydnie
int shot_line[2];
int AI_no;
int A_meirei;
int B_meirei;
char syouri[41];
char serihu[61];
char setu_1[61];
char setu_2[61];
char setu_3[61];
char jin_name[2][22];
char sikikan_name[2][22];
char hero_name[22];//主人公の名前
char save_name[3][22];//セーブデータの主人公名
int save_syuu[3];//セーブデータの週
int save_time[3];//セーブデータのプレイ時間
int play_time;//プレイ時間
int time_count;//時間経過計算用
int min_hen;
int koku_hen;
int san_hen;
int kane_hen;
char font_name[40];
int ame;
int tenki;
int tenkou;//天気変化残り時間
int VS_no;
int con_time;
int moritami;
int boss;
int majyo;
int hensei_no;
int MSN;
int kokuryoku;
int tairetu[6];
int kasoku;//戦闘加速
int name_set;
char moji_set[14][221][3];
int VS_aite;
int item_g[15];
int omake_rensen;//おまけ連戦回数
int bgm[4];
int bamen[4];//イベントシーン用
int se_no[20];//効果音用
int ex_mode;
int pow_lv[100];//攻撃力レベル最大１００
int def_lv[100];//防御力レベル最大１００
int spd_lv[100];//スピードレベル最大１００
int wei_lv[100];//踏ん張りレベル最大１００
int sta_lv[100];//スタミナレベル最大１００
int kaz_lv[100];//生命力レベル最大９９９９
int ran_gundan[100];
int ura_mode;//裏モードフラグ
int VS_result;//1全滅勝利 2退却勝利 3生き残り勝利 4全滅敗北 5退却敗北 6生き残り敗北 7生き残り引き分け
int shot_x[100];//射撃Ｘ座標
int shot_y[100];//射撃Ｙ座標
int shot_h[100];//射撃高さ
int shot_mu[100];//射撃向き
int shot_col[100];//射撃色
int shot_vx[100];//射撃Ｘ速度
int shot_vy[100];//射撃Ｙ速度
int shot_vh[100];//射撃Ｈ速度
int shot_time[100];//着弾までの時間
int magic_g[10][8];
int back[11];